apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: elasticsearch
subjects:
  - kind: ServiceAccount
    name: elasticsearch
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: elasticsearch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: elasticsearch
rules:
  - nonResourceURLs:
    - /
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
  - apiGroups:
    - apps
    resources:
    - statefulsets/status
    verbs:
    - get
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-ingest
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: ingest
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      component: ingest
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        component: ingest
    spec:
      serviceAccountName: elasticsearch
      initContainers:
        - name: memory-map-increase
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
      containers:
        - name: elasticsearch-ingest
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_MASTER
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          emptyDir: {}
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      component: master
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        component: master
    spec:
      serviceAccountName: elasticsearch
      initContainers:
        - name: memory-map-increase
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
      containers:
        - name: elasticsearch-master
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          ports:
            - name: transport
              containerPort: 9300
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_MASTER
              value: "true"
            - name: NODE_DATA
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          emptyDir: {}
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: data
spec:
  serviceName: elasticsearch-data
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
      component: data
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        component: data
    spec:
      serviceAccountName: elasticsearch
      initContainers:
        - name: memory-map-increase
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
      containers:
        - name: elasticsearch-data
          image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          ports:
            - name: http
              containerPort: 9200
            - name: transport
              containerPort: 9300
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 5
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_MASTER
              value: "false"
            - name: NODE_DATA
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: storage
              mountPath: /data
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: monitoring
data:
  elasticsearch.yml: |
    xpack:
      security:
        enabled: false
    cluster:
      name: elasticsearch
    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
        minimum_master_nodes: 1
    http:
      enabled: ${HTTP_ENABLE}
      compression: true
    network:
      host: 0.0.0.0
    node:
      master: ${NODE_MASTER}
      data: ${NODE_DATA}
      ingest: ${NODE_INGEST}
      name: ${NODE_NAME}
      max_local_storage_nodes: 3
    path:
      data: /usr/share/elasticsearch/data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: ingest
spec:
  selector:
    k8s-app: elasticsearch
    component: ingest
  ports:
  - name: http
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: master
spec:
  selector:
    k8s-app: elasticsearch
    component: master
  ports:
  - name: transport
    port: 9300
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data
  namespace: monitoring
  labels:
    k8s-app: elasticsearch
    component: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    k8s-app: elasticsearch
    component: data
